Repository openwisp/openwisp-controller, pull requests merged in 2021-03, with the labels that each got.

#397 [feature] Implemented caching of device checksum view #396
  openwisp_controller/config/apps.py
  openwisp_controller/config/base/config.py
  openwisp_controller/config/controller/views.py
  openwisp_controller/config/tests/test_config.py
  openwisp_controller/config/tests/test_controller.py
  openwisp_controller/config/utils.py
  requirements.txt
Labels: enhancement

#408 [fix] Update related config when template default_values are changed
  openwisp_controller/config/base/template.py
  openwisp_controller/config/tests/test_template.py
Labels: enhancement

#369 [admin] Added dashboard chart for devices based on configuration status
  .github/workflows/ci.yml
  Dockerfile
  README.rst
  install-dev.sh
  openwisp_controller/config/apps.py
  openwisp_controller/config/tests/test_app.py
  openwisp_controller/config/tests/test_apps.py
  openwisp_controller/config/tests/test_notifications.py
  openwisp_controller/geo/admin.py
  openwisp_controller/geo/apps.py
  openwisp_controller/geo/tests/test_apps.py
  requirements-test.txt
  requirements.txt
  tests/openwisp2/sample_config/tests.py
  tests/openwisp2/sample_geo/tests.py
Labels: Important, enhancement

#409 [change] Move changes check to save methods
  openwisp_controller/config/base/config.py
  openwisp_controller/config/base/device.py
  openwisp_controller/config/tests/test_config.py
  openwisp_controller/config/tests/test_device.py
Labels: enhancement

#411 [fix] Fixed unsaved_changes.js when location is present #388
  openwisp_controller/config/static/config/js/unsaved_changes.js
  openwisp_controller/config/static/config/js/widget.js
Labels: bug
