Repository openwisp/openwisp-controller, pull requests merged in 2024-07, with the labels that each got.

#865 [change] Notify users of background subnet division rule errors #837
  openwisp_controller/subnet_division/rule_types/base.py
  openwisp_controller/subnet_division/tests/test_models.py
  tests/openwisp2/sample_subnet_division/tests.py
Labels: subnet-division-rules

#875 [chores] Optimized Template._update_related_config_status
  openwisp_controller/config/base/template.py
  openwisp_controller/config/tests/test_template.py
  openwisp_controller/connection/apps.py
  openwisp_controller/connection/tasks.py
  openwisp_controller/connection/tests/test_models.py
Labels: enhancement

#876 [fix] JS workaround for using mac address variable
  openwisp_controller/config/static/config/js/widget.js
Labels: bug

#883 [ci] Run on Ubuntu 24.04 LTS
  .github/workflows/ci.yml
Labels: enhancement

#884 [deps] Bumped paramiko to ~=3.4.0
  requirements.txt
Labels: enhancement
