Repository openwisp/openwisp-controller, pull requests merged in 2025-09, with the labels that each got.

#1112 [fix] Avoid re-populating peer cache in post_save to prevent slow requests
  openwisp_controller/config/base/vpn.py
  openwisp_controller/config/tasks.py
  openwisp_controller/config/tests/test_vpn.py
  openwisp_controller/config/tests/utils.py
Labels: bug

#1093 [fix] Fixed DeviceConnection and Command API endpoints for non-superuser
  openwisp_controller/connection/api/views.py
  openwisp_controller/connection/tests/test_api.py
  openwisp_controller/mixins.py
Labels: bug

#1120 [fix] Added "default" kwarg for unique nullable fields
  openwisp_controller/pki/api/serializers.py
Labels: enhancement

#1127 [tests] Moved test logic to dedicated script
  .github/workflows/ci.yml
  docs/developer/installation.rst
  runtests
Labels: testing

#1129 [fix] Fixed device group filter label in device list #1071
  openwisp_controller/config/filters.py
Labels: enhancement
