Repository openwisp/openwisp-controller, pull requests merged in 2025-05, with the labels that each got.

#1012 [ci] Show build errors
  .github/workflows/ci.yml
Labels: enhancement

#1015 [change] REST API cleanup and consistency
  openwisp_controller/config/api/serializers.py
  openwisp_controller/config/api/urls.py
  openwisp_controller/config/api/views.py
  openwisp_controller/config/base/config.py
  openwisp_controller/config/tests/test_api.py
  openwisp_controller/connection/api/serializers.py
  openwisp_controller/connection/api/urls.py
  openwisp_controller/connection/api/views.py
  openwisp_controller/connection/apps.py
  openwisp_controller/connection/base/models.py
  openwisp_controller/connection/tests/test_api.py
  openwisp_controller/geo/api/serializers.py
  openwisp_controller/pki/api/serializers.py
  openwisp_controller/pki/api/urls.py
  openwisp_controller/pki/tests/test_api.py
  openwisp_controller/serializers.py
Labels: enhancement

#1014 [fix] Fixed unsaved changes alert for readonly map #560
  openwisp_controller/config/static/config/js/unsaved_changes.js
  openwisp_controller/geo/tests/test_selenium.py
  openwisp_controller/geo/tests/utils.py
Labels: bug

#1017 [fix] Fixed live updates for "Send commands"
  openwisp_controller/connection/channels/consumers.py
  openwisp_controller/connection/tests/pytest.py
Labels: bug

#1041 [chores] Changed device_pk to device_id for consistency with docs
  openwisp_controller/connection/api/urls.py
  openwisp_controller/connection/api/views.py
  openwisp_controller/connection/apps.py
  openwisp_controller/connection/tasks.py
Labels: docs

#1031 [fix] Fixed handling of non-existing device in DeviceLocationView
  openwisp_controller/geo/api/views.py
  openwisp_controller/geo/tests/test_api.py
  openwisp_controller/mixins.py
Labels: bug

#1020 [fix] Do not allow applying more than 1 templates of same VPN server #832
  openwisp_controller/config/base/config.py
  openwisp_controller/config/tests/test_api.py
  openwisp_controller/config/tests/test_config.py
  openwisp_controller/config/tests/test_vpn.py
Labels: bug

#1059 [fix:1.1] Do not allow applying more than 1 templates of same VPN server #832
  openwisp_controller/config/base/config.py
  openwisp_controller/config/tests/test_api.py
  openwisp_controller/config/tests/test_config.py
  openwisp_controller/config/tests/test_vpn.py
Labels: bug

#1060 [fix:tests] Updated test_zerotier_vpn_client_template #832
  openwisp_controller/config/tests/test_vpn.py
Labels: bug
