Repository openwisp/openwisp-controller, pull requests merged in 2025-07, with the labels that each got.

#1069 [change] Switched 'Background API Task' notification to 'Generic Mess…
  openwisp_controller/config/apps.py
  openwisp_controller/config/migrations/0060_cleanup_api_task_notification_types.py
  openwisp_controller/config/tasks_zerotier.py
  openwisp_controller/config/tests/test_notifications.py
Labels: enhancement

#1085 [tests] Sessions now cached in redis
  openwisp_controller/config/tests/test_admin.py
  openwisp_controller/config/tests/test_api.py
  openwisp_controller/config/tests/test_views.py
  openwisp_controller/connection/tests/test_api.py
  openwisp_controller/geo/tests/test_api.py
  openwisp_controller/pki/tests/test_api.py
  tests/openwisp2/settings.py
Labels: enhancement

#1092 [fix] Fixed visibility of "Recent Commands" tab on device page
  openwisp_controller/connection/static/connection/css/command-inline.css
  openwisp_controller/connection/tests/test_selenium.py
Labels: bug

#976 [feature] Add API endpoint for indoor map coordinates #828
  docs/user/rest-api.rst
  openwisp_controller/geo/api/serializers.py
  openwisp_controller/geo/api/views.py
  openwisp_controller/geo/tests/test_api.py
  openwisp_controller/geo/utils.py
  tests/openwisp2/sample_geo/views.py
Labels: gsoc

#1099 [fix] Don't delete VpnClients when enforcing required templates
  openwisp_controller/config/base/config.py
  openwisp_controller/config/tests/test_admin.py
Labels: bug
